# Generated by Django 5.1.2 on 2024-11-08 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(default=1, help_text='Day number when this message should be sent')),
                ('name', models.CharField(help_text='Template name for identification', max_length=100)),
                ('english_template', models.TextField(help_text='Message template in English. Use {name} for recipient name.')),
                ('hindi_template', models.TextField(help_text='Message template in Hindi. Use {name} for recipient name.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['day_number'],
                'indexes': [models.Index(fields=['day_number'], name='whatsapp_me_day_num_28b8ee_idx'), models.Index(fields=['is_active'], name='whatsapp_me_is_acti_39b04f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='WhatsApp number with country code (e.g., +911234567890)', max_length=15, unique=True)),
                ('name', models.CharField(help_text="Recipient's full name", max_length=100)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', help_text='Preferred language for communication', max_length=2)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the recipient is active and should receive messages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number'], name='whatsapp_re_phone_n_111cb1_idx'), models.Index(fields=['is_active'], name='whatsapp_re_is_acti_6985a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='Twilio message ID for tracking', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='whatsapp.messagetemplate')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='whatsapp.recipient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='whatsapp_me_status_e1bf0d_idx'), models.Index(fields=['sent_at'], name='whatsapp_me_sent_at_c3434b_idx'), models.Index(fields=['created_at'], name='whatsapp_me_created_37387d_idx')],
            },
        ),
    ]
