# Generated by Django 5.1.2 on 2024-11-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(blank=True, help_text="Recipient's full name", max_length=100, null=True),
        ),
    ]
