# Generated by Django 5.1.2 on 2024-11-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_alter_recipient_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quotes',
            index=models.Index(fields=['quote'], name='whatsapp_qu_quote_c425fe_idx'),
        ),
    ]
