# Generated by Django 5.1.2 on 2024-11-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_quotes_whatsapp_qu_quote_c425fe_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='subscription_day_number',
            field=models.IntegerField(default=1, help_text='Day number when the user subscribed and will increment after every message.'),
        ),
    ]
