# Generated by Django 5.1.2 on 2024-11-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_recipient_subscription_day_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='link',
            field=models.URLField(blank=True, help_text='Optional URL to send along with the template message', null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.TextField(help_text='Quotes from swami vivekananda'),
        ),
    ]
