# Generated by Django 5.1.2 on 2024-11-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_recipient_email_alter_messagelog_status_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='current_plan',
            field=models.CharField(blank=True, help_text='Currently active plan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='payment_status',
            field=models.CharField(default='pending', help_text='Status of latest payment', max_length=20),
        ),
        migrations.AddField(
            model_name='recipient',
            name='pending_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Amount pending for selected plan', null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='pending_plan',
            field=models.CharField(blank=True, help_text='Plan selected but not yet paid for', max_length=100, null=True),
        ),
    ]
