# Generated by Django 5.1.2 on 2024-11-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_recipient_current_plan_recipient_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='current_state',
            field=models.CharField(default='MAIN_MENU', max_length=50),
        ),
    ]
