# Generated by Django 5.1.2 on 2024-11-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_recipient_current_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='current_state',
        ),
        migrations.AddField(
            model_name='recipient',
            name='selected_plan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
