# Generated by Django 5.1.2 on 2024-11-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_remove_recipient_current_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(blank=True, default='New_User', help_text="Recipient's full name", max_length=100),
        ),
    ]
