# Generated by Django 5.1.2 on 2024-11-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0011_alter_recipient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='english_template',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='hindi_template',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='link',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='template_id',
            field=models.CharField(default='nil', help_text='Unique ID for the template to send', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
